project_name: quellog

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: quellog
    binary: quellog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: quellog
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: quellog
    package_name: quellog
    vendor: Alain Lesage
    homepage: https://github.com/Alain-L/quellog
    maintainer: Alain Lesage <alain.lesage@dalibo.com>
    description: High-performance PostgreSQL log parser and analyzer
    license: PostgreSQL
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/quellog/LICENSE
      - src: README.md
        dst: /usr/share/doc/quellog/README.md
      - src: CHANGELOG.md
        dst: /usr/share/doc/quellog/CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: Alain-L
    name: quellog
  draft: false
  prerelease: auto