package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"regexp"
	"strings"
	"sync"

	"github.com/Alain-L/quellog/analysis"
	"github.com/Alain-L/quellog/web"
	"github.com/klauspost/compress/zstd"
)

// Cached template data (computed once on first use)
var (
	tmplData     *reportTemplateData
	tmplDataOnce sync.Once
	tmpl         *template.Template
	tmplOnce     sync.Once
)

// reportTemplateData holds pre-computed template values
type reportTemplateData struct {
	CSS      template.CSS
	Body     template.HTML
	UplotJS  template.JS
	FzstdB64 string
	AppJS    template.JS
}

// HTMLReportInfo contains metadata about the report generation.
type HTMLReportInfo struct {
	Filename    string
	FileSize    int64
	ProcessTime float64 // in milliseconds
	Format      string  // detected log format (csv, json, stderr)
	Version     string  // quellog version for display in the report
}

// minifyCSS performs basic CSS minification.
func minifyCSS(css string) string {
	// Remove comments
	css = regexp.MustCompile(`/\*.*?\*/`).ReplaceAllString(css, "")
	// Collapse whitespace
	css = regexp.MustCompile(`\s+`).ReplaceAllString(css, " ")
	// Remove space around punctuation
	css = regexp.MustCompile(`\s*([{};:,])\s*`).ReplaceAllString(css, "$1")
	// Remove trailing semicolons before }
	css = regexp.MustCompile(`;\s*}`).ReplaceAllString(css, "}")
	return strings.TrimSpace(css)
}

// extractBodyContent extracts content between <body> and <script from index.html
func extractBodyContent(html string) string {
	re := regexp.MustCompile(`(?s)<body>(.*?)<script`)
	match := re.FindStringSubmatch(html)
	if len(match) > 1 {
		body := strings.TrimSpace(match[1])
		// Change header subtitle for report mode
		body = strings.Replace(body,
			"WebAssembly demo – all processing happens locally in your browser",
			"Report generated by CLI",
			1)
		return body
	}
	return ""
}

// gzipBase64 compresses data with gzip and encodes to base64.
func gzipBase64(data string) string {
	var buf bytes.Buffer
	gz, _ := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	gz.Write([]byte(data))
	gz.Close()
	return base64.StdEncoding.EncodeToString(buf.Bytes())
}

// getTemplateData returns cached template data (computed once).
func getTemplateData() *reportTemplateData {
	tmplDataOnce.Do(func() {
		tmplData = &reportTemplateData{
			CSS:      template.CSS(minifyCSS(web.StylesCSS)),
			Body:     template.HTML(extractBodyContent(web.IndexHTML)),
			UplotJS:  template.JS(web.UplotJS),
			FzstdB64: gzipBase64(web.FzstdJS),
			AppJS:    template.JS(web.AppBundleJS),
		}
	})
	return tmplData
}

// getTemplate returns the parsed template (computed once).
func getTemplate() *template.Template {
	tmplOnce.Do(func() {
		tmpl = template.Must(template.New("report").Parse(web.ReportTmpl))
	})
	return tmpl
}

// templateValues holds all values for template execution
type templateValues struct {
	CSS            template.CSS
	Body           template.HTML
	UplotJS        template.JS
	FzstdB64       string
	AppJS          template.JS
	CompressedData string
	Version        string
}

// splitPeriod is one selectable period in a split report. Entries and Errors
// drive the timeline navigator (bar height and error tint).
type splitPeriod struct {
	Label   string
	Entries int
	Errors  int
	Data    string // zstd + base64 compressed JSON for this period
}

// splitTemplateValues holds the values for the split (multi-period) report.
type splitTemplateValues struct {
	CSS       template.CSS
	Body      template.HTML
	UplotJS   template.JS
	FzstdB64  string
	AppJS     template.JS
	Periods   []splitPeriod
	TotalSize string // human-readable total input size, shown in the eyebrow
	Version   string
}

var splitTmpl *template.Template

// getSplitTemplate returns the parsed split-report template (computed once).
func getSplitTemplate() *template.Template {
	if splitTmpl == nil {
		splitTmpl = template.Must(template.New("report_split").Parse(web.ReportSplitTmpl))
	}
	return splitTmpl
}

// compressReportJSON builds the embedded-report JSON for one set of metrics and
// returns it zstd-compressed and base64-encoded (the form the template embeds).
func compressReportJSON(metrics analysis.AggregatedMetrics, info HTMLReportInfo, sections []string) (string, error) {
	data := buildJSONData(metrics, []string{"all"}, true)
	format := info.Format
	if format == "" {
		format = "stderr"
	}
	data["meta"] = map[string]interface{}{
		"format":        format,
		"entries":       metrics.Global.Count,
		"filename":      info.Filename,
		"filesize":      info.FileSize,
		"parse_time_ms": info.ProcessTime,
		"sections":      sections,
	}
	jsonBytes, err := json.Marshal(data)
	if err != nil {
		return "", fmt.Errorf("failed to marshal metrics to JSON: %w", err)
	}
	var zstdBuf bytes.Buffer
	zstdWriter, err := zstd.NewWriter(&zstdBuf, zstd.WithEncoderLevel(zstd.SpeedBestCompression))
	if err != nil {
		return "", fmt.Errorf("failed to create zstd writer: %w", err)
	}
	if _, err := zstdWriter.Write(jsonBytes); err != nil {
		return "", fmt.Errorf("failed to compress JSON: %w", err)
	}
	if err := zstdWriter.Close(); err != nil {
		return "", fmt.Errorf("failed to close zstd writer: %w", err)
	}
	return base64.StdEncoding.EncodeToString(zstdBuf.Bytes()), nil
}

// ExportHTMLSplit exports a single standalone HTML report holding one embedded
// dataset per time period, with a selector to switch between them.
func ExportHTMLSplit(w io.Writer, buckets []analysis.SplitBucket, info HTMLReportInfo, sections []string) error {
	periods := make([]splitPeriod, 0, len(buckets))
	for _, b := range buckets {
		bi := info
		// Keep the source identity (e.g. "13 files") as the filename; the
		// period label is shown by the navigator, not duplicated here.
		bi.FileSize = 0
		compressed, err := compressReportJSON(b.Metrics, bi, sections)
		if err != nil {
			return err
		}
		g := b.Metrics.Global
		periods = append(periods, splitPeriod{
			Label:   b.Label,
			Entries: g.Count,
			Errors:  g.ErrorCount + g.FatalCount + g.PanicCount,
			Data:    compressed,
		})
	}

	totalSize := ""
	if info.FileSize > 0 {
		totalSize = FormatBytes(info.FileSize)
	}

	td := getTemplateData()
	values := splitTemplateValues{
		CSS:       td.CSS,
		Body:      td.Body,
		UplotJS:   td.UplotJS,
		FzstdB64:  td.FzstdB64,
		AppJS:     td.AppJS,
		Periods:   periods,
		TotalSize: totalSize,
		Version:   info.Version,
	}
	if err := getSplitTemplate().Execute(w, values); err != nil {
		return fmt.Errorf("failed to execute split template: %w", err)
	}
	return nil
}

// ExportHTML exports metrics as a standalone HTML report with embedded data.
func ExportHTML(w io.Writer, metrics analysis.AggregatedMetrics, info HTMLReportInfo, sections []string) error {
	// Build full JSON data structure (same as JSON export with all sections)
	data := buildJSONData(metrics, []string{"all"}, true)

	// Add meta section required by the web UI
	format := info.Format
	if format == "" {
		format = "stderr" // default
	}
	data["meta"] = map[string]interface{}{
		"format":        format,
		"entries":       metrics.Global.Count,
		"filename":      info.Filename,
		"filesize":      info.FileSize,
		"parse_time_ms": info.ProcessTime,
		"sections":      sections,
	}

	// Marshal to JSON
	jsonBytes, err := json.Marshal(data)
	if err != nil {
		return fmt.Errorf("failed to marshal metrics to JSON: %w", err)
	}

	// Compress JSON with zstd using klauspost's SpeedBestCompression
	// preset (its strongest level, not the CLI's -19).
	var zstdBuf bytes.Buffer
	zstdWriter, err := zstd.NewWriter(&zstdBuf, zstd.WithEncoderLevel(zstd.SpeedBestCompression))
	if err != nil {
		return fmt.Errorf("failed to create zstd writer: %w", err)
	}
	if _, err := zstdWriter.Write(jsonBytes); err != nil {
		return fmt.Errorf("failed to compress JSON: %w", err)
	}
	if err := zstdWriter.Close(); err != nil {
		return fmt.Errorf("failed to close zstd writer: %w", err)
	}

	// Encode to base64
	compressed := base64.StdEncoding.EncodeToString(zstdBuf.Bytes())

	// Get cached template data
	td := getTemplateData()

	// Execute template with all values
	values := templateValues{
		CSS:            td.CSS,
		Body:           td.Body,
		UplotJS:        td.UplotJS,
		FzstdB64:       td.FzstdB64,
		AppJS:          td.AppJS,
		CompressedData: compressed,
		Version:        info.Version,
	}

	if err := getTemplate().Execute(w, values); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}
