package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"regexp"
	"strings"
	"sync"

	"github.com/Alain-L/quellog/analysis"
	"github.com/Alain-L/quellog/web"
	"github.com/klauspost/compress/zstd"
)

// Cached template data (computed once on first use)
var (
	tmplData     *reportTemplateData
	tmplDataOnce sync.Once
	tmpl         *template.Template
	tmplOnce     sync.Once
)

// reportTemplateData holds pre-computed template values
type reportTemplateData struct {
	CSS      template.CSS
	Body     template.HTML
	UplotJS  template.JS
	FzstdB64 string
	AppJS    template.JS
}

// HTMLReportInfo contains metadata about the report generation.
type HTMLReportInfo struct {
	Filename    string
	FileSize    int64
	ProcessTime float64 // in milliseconds
	Format      string  // detected log format (csv, json, stderr)
}

// minifyCSS performs basic CSS minification.
func minifyCSS(css string) string {
	// Remove comments
	css = regexp.MustCompile(`/\*.*?\*/`).ReplaceAllString(css, "")
	// Collapse whitespace
	css = regexp.MustCompile(`\s+`).ReplaceAllString(css, " ")
	// Remove space around punctuation
	css = regexp.MustCompile(`\s*([{};:,])\s*`).ReplaceAllString(css, "$1")
	// Remove trailing semicolons before }
	css = regexp.MustCompile(`;\s*}`).ReplaceAllString(css, "}")
	return strings.TrimSpace(css)
}

// extractBodyContent extracts content between <body> and <script from index.html
func extractBodyContent(html string) string {
	re := regexp.MustCompile(`(?s)<body>(.*?)<script`)
	match := re.FindStringSubmatch(html)
	if len(match) > 1 {
		body := strings.TrimSpace(match[1])
		// Change header subtitle for report mode
		body = strings.Replace(body,
			"WebAssembly demo – all processing happens locally in your browser",
			"Report generated by CLI",
			1)
		return body
	}
	return ""
}

// gzipBase64 compresses data with gzip and encodes to base64.
func gzipBase64(data string) string {
	var buf bytes.Buffer
	gz, _ := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	gz.Write([]byte(data))
	gz.Close()
	return base64.StdEncoding.EncodeToString(buf.Bytes())
}

// getTemplateData returns cached template data (computed once).
func getTemplateData() *reportTemplateData {
	tmplDataOnce.Do(func() {
		tmplData = &reportTemplateData{
			CSS:      template.CSS(minifyCSS(web.StylesCSS)),
			Body:     template.HTML(extractBodyContent(web.IndexHTML)),
			UplotJS:  template.JS(web.UplotJS),
			FzstdB64: gzipBase64(web.FzstdJS),
			AppJS:    template.JS(web.AppBundleJS),
		}
	})
	return tmplData
}

// getTemplate returns the parsed template (computed once).
func getTemplate() *template.Template {
	tmplOnce.Do(func() {
		tmpl = template.Must(template.New("report").Parse(web.ReportTmpl))
	})
	return tmpl
}

// templateValues holds all values for template execution
type templateValues struct {
	CSS            template.CSS
	Body           template.HTML
	UplotJS        template.JS
	FzstdB64       string
	AppJS          template.JS
	CompressedData string
}

// ExportHTML exports metrics as a standalone HTML report with embedded data.
func ExportHTML(w io.Writer, metrics analysis.AggregatedMetrics, info HTMLReportInfo, sections []string) error {
	// Build full JSON data structure (same as JSON export with all sections)
	data := buildJSONData(metrics, []string{"all"}, true)

	// Add meta section required by the web UI
	format := info.Format
	if format == "" {
		format = "stderr" // default
	}
	data["meta"] = map[string]interface{}{
		"format":        format,
		"entries":       metrics.Global.Count,
		"filename":      info.Filename,
		"filesize":      info.FileSize,
		"parse_time_ms": info.ProcessTime,
		"sections":      sections,
	}

	// Marshal to JSON
	jsonBytes, err := json.Marshal(data)
	if err != nil {
		return fmt.Errorf("failed to marshal metrics to JSON: %w", err)
	}

	// Compress JSON with zstd (level 19 for best compression)
	var zstdBuf bytes.Buffer
	zstdWriter, err := zstd.NewWriter(&zstdBuf, zstd.WithEncoderLevel(zstd.SpeedBestCompression))
	if err != nil {
		return fmt.Errorf("failed to create zstd writer: %w", err)
	}
	if _, err := zstdWriter.Write(jsonBytes); err != nil {
		return fmt.Errorf("failed to compress JSON: %w", err)
	}
	if err := zstdWriter.Close(); err != nil {
		return fmt.Errorf("failed to close zstd writer: %w", err)
	}

	// Encode to base64
	compressed := base64.StdEncoding.EncodeToString(zstdBuf.Bytes())

	// Get cached template data
	td := getTemplateData()

	// Execute template with all values
	values := templateValues{
		CSS:            td.CSS,
		Body:           td.Body,
		UplotJS:        td.UplotJS,
		FzstdB64:       td.FzstdB64,
		AppJS:          td.AppJS,
		CompressedData: compressed,
	}

	if err := getTemplate().Execute(w, values); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}
